package polischukovik;

public enum PropertyName {
	BASIC_TEST_NAME,
	T_VARIANT_TITLE,
	T_KEY_TITLE,
	BASIC_VARIANTS,
	BASIC_QUESTIONS,
	PARSING_MARK_QUESTION,
	PARSING_MARK_CORRECT_ANSWER,
	IO_SOURCE_FILE_NAME,
	IO_DEST_FILE_NAME,
	P_PUNCTUATION_QUESTION,
	P_PUNCTUATION_ANSWER,
	P_PUNCTUATION_KEY_ANSWER,
	F_QUESTION_BOLD,
	F_QUESTION_SPACING,
	S_NUMERATION_VARIANT,
	S_NUMERATION_QUESTION,
	S_NUMERATION_ANSWER,
	P_SHUFFLE_QUESTION,
	P_SHUFFLE_ANSWERS;
	
	
}
